
server:
  port: 4001

spring:
  application:
    name: WebServer
  datasource:
    url: jdbc:h2:mem:student
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  http:
    encoding:
      charset: UTF-8
